### ISSUE TITLE
Feature request. Examples

### ISSUE THREAD

**Issue by Gargo** [gonzalonunez/Walt#1]

**Comment by gonzalonunez** [comment]
Working on it :)

**Comment by gonzalonunez** [comment]
What would you like to see as an example? I originally decided not to include an example project because I thought the functionality was pretty straight forward.

**Comment by Gargo** [comment]
Just something to watch that this library works without of manual creating of a new project

**Comment by gonzalonunez** [comment]
Ok cool, hadn't realized that's what happens without an example. Thanks!

**Comment by gonzalonunez** [comment]
Hi! Finally got around to creating an Example project. You'll find it in the `Example/` directory.
