### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by AdventuresOfMar** [gonzalonunez/Walt#2]
Hello Gonza!
Hope everything is amazing for you, also really enjoy your website. I'm a bit confused about how this pod works. I'm attempting to download your project folder but i get the following error, The operation can’t be completed because the original item for “_Pods.xcodeproj” can’t be found. Any suggestions?

**Comment by gonzalonunez** [comment]
Hey!

Thank you, I appreciate that! So, in short, that `_Pods.xcodeproj` is just an alias created by Cocoapods. It's used when there's an example project with the Pod, which in this case there currently is not (sorry, I've been pretty swamped lately!).

If you'd like to mess around with this library, I'd suggest either:

1. Copying the files inside of the Source directory into an **Xcode project that you've created**

or

2. Creating a new project and use Cocoapods to add the dependency

**Comment by gonzalonunez** [comment]
Eventually, there will be a quick and easy example project. The reason there currently isn't one is because I simply used an existing app of mine to create and test this library.

**Comment by gonzalonunez** [comment]
Hi! Finally got around to creating an Example project. You'll find it in the `Example/` directory.
