### ISSUE TITLE
Make the video play-through once without looping

### ISSUE THREAD

**Issue by thereal1** [gonzalonunez/Walt#4]
Is it possible to make the video play-through with a set duration and not loop, I first tried setting the loop duration to 0 but this just seems to crash the app.

Also, is there a way to set the amount of time each image shows for? Or just this just directly correlate with the duration?

Thanks.

**Comment by gonzalonunez** [comment]
Hi!

Yes this is possible, can I see the code you're using to generate the video? I think you'd be fine just setting your `loopDuration` to whatever your `totalDuration` is so that it only loops once. Let me know if this does the trick 👍🏻

It's a little confusing now that I think about it 😅

**Comment by thereal1** [comment]
Setting the loopDuration and duration to the same value doesn't seem to work, it still loops twice.

Heres my code(sorry for the code formatting, I cant get the markdown to work correctly)

```
try! Walt.writeMovie(with: images, options: MovieWritingOptions(loopDuration: 1.0, duration: Int(1.0), shouldOverwrite: true)) { (fileUrl, data) in
            self.player = AVPlayer(url: fileUrl)
            let playerLayer = AVPlayerLayer(player: self.player)
            
            playerLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
            playerLayer.frame =  self.baseView.bounds
            
            self.baseView.layer.addSublayer(playerLayer)
            self.baseView.playerLayer = playerLayer
        }
```

**Comment by gonzalonunez** [comment]
Hmmm something must be going on here: https://github.com/gonzalonunez/Walt/blob/ab2e39e92ac400a6099aa756804b84dc040eda4a/Walt/Source/Walt.swift#L61

When I evaluate that in the Swift REPL I get `1` though. Anyways, can you set a breakpoint on line 71 and let me know what `iterations` and `finalVideoArray` look like? I'm about to pull something up to test this as well.

**Comment by gonzalonunez** [comment]
Found the bug! The `for` loop was off by one 😳

Pushing up a fix that also included an example app, I'll update the podspec as well. Let me know if this works for you once I do!

**Comment by gonzalonunez** [comment]
Let me know if this did the trick. Just pushed up the changes to Cocoapods 👍

**Comment by thereal1** [comment]
Yes that fixed it. Thank you 🤘🏼

**Comment by gonzalonunez** [comment]
No prob! Hope you're enjoying the library 😄
